# Generated by Django 4.2.7 on 2026-03-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clustering_data', models.JSONField(blank=True, null=True)),
                ('prediction_data', models.JSONField(blank=True, null=True)),
                ('avg_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('savings_suggestion', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Insight',
                'verbose_name_plural': 'Expense Insights',
            },
        ),
    ]
