# Generated by Django 4.2.7 on 2026-03-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORTATION', 'Transportation'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
